name: esplora
description: Wraps blockstream esplora.
version: 1.0.0
homepage: https://github.com/ethicnology/dart-esplora

environment:
  sdk: '>=2.16.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
dependencies: 
  http: ^0.13.4
